# https://taskfile.dev

version: "3"

tasks:
  helm-repo-add:
    desc: Add Helm repo
    vars:
      REPO_NAME: "{{.REPO_NAME}}"
      REPO_URL: "{{.REPO_URL}}"
    cmds:
      - helm repo add "{{.REPO_NAME}}" "{{.REPO_URL}}"
      - helm repo update
    status:
      - helm repo list  | grep -qE '{{.REPO_NAME}}\s*{{.REPO_URL}}'
    silent: true

  helm-install:
    desc: Install Helm Chart
    vars:
      NAMESPACE: '{{default "default" .NAMESPACE}}'
      REPO: '{{default "" .REPO}}'
      CHART: "{{.CHART}}"
      VALUES_FILE: '{{default "" .VALUES_FILE}}'
      ARGS: '{{default "" .ARGS}}'
      RELEASE: "{{default .CHART .RELEASE}}"
      FORCE: '{{default "" .FORCE}}'
    cmds:
      - |
        [[ -n "{{.VALUES_FILE}}" ]] && THIS_VALUES='-f {{.VALUES_FILE}}' || THIS_VALUES=""
        [[ -n "{{.REPO}}" ]] && THIS_REPO='{{.REPO}}/' || THIS_REPO=""
        helm upgrade \
          --dependency-update \
          --install {{.RELEASE}} ${THIS_VALUES} ${THIS_REPO}{{.CHART}} --namespace "{{.NAMESPACE}}" --create-namespace {{.ARGS}}
    status:
      - |
        [[ -z "${FORCE}" ]] && helm status -n "{{.NAMESPACE}}" "{{.RELEASE}}" || false

  helm-upgrade-nginx:
    cmds:
      - task: helm-repo-add
        vars:
          REPO_NAME: ingress-nginx
          REPO_URL: https://kubernetes.github.io/ingress-nginx
      - task: helm-install
        vars:
          NAMESPACE: "nginx"
          CHART: ingress-nginx
          REPO: ingress-nginx
          VALUES_FILE: values/nginx.yaml
      - kubectl rollout status -n nginx deployment ingress-nginx-controller -w

  deploy-echo-server:
    cmds:
      - task: helm-repo-add
        vars:
          REPO_NAME: ealenn
          REPO_URL: https://ealenn.github.io/charts
      - task: helm-install
        vars:
          NAMESPACE: "echo-server"
          CHART: echo-server
          REPO: ealenn
          VALUES_FILE: values/echo-server.yaml
      - kubectl rollout status -n echo-server deployment echo-server -w

  default:
    cmds:
      - kubectl cluster-info
